### PR TITLE
Add Item.clear built-in function

### PR DESCRIPTION
**Pull request by Nico314159**

### CODE REVIEW

**Comment by WingedSeal** [comment]
Why is "amount" `ANY` type? Set the defaults to 1 and check whether it is 1

**Comment by Nico314159** [comment]
> Why is "amount" `ANY` type? Set the defaults to 1 and check whether it is 1

That won't be able to distinguish between someone actually inputting 1 and someone leaving off that input. (leaving off the input clears *all* copies of the specified item not just 1)

**Comment by Nico314159** [comment]
I guess I could use -1 for that purpose tho

**Comment by WingedSeal** [comment]
But there's literally no difference between someone actually inputting 1 and someone leaving off that input.

**Comment by Nico314159** [comment]
> But there's literally no difference between someone actually inputting 1 and someone leaving off that input.

No, `clear @s gold_block` and `clear @s gold_block 1` do different things. The former removes *all* gold blocks from inventory, the latter only removes 1 gold block.

**Comment by Nico314159** [comment]
Okay I changed it.

**Comment by Nico314159** [comment]
> I didn't see any change...

I forgot to push 🤦

**Pull request merged**
